### ISSUE TITLE
Is it possible to save audio recording ?

### ISSUE THREAD

**Issue by e-rasvet** [aws-samples/amazon-transcribe-websocket-static#13]
Hello!

Is it possible to put audio recording blob link to console, when transcribe be finished? (webm, wav or mp3)

**Comment by brandonmwest** [comment]
From a static website you could only store the file in memory, so you could provide a link but it wouldn't persist. An example would be https://github.com/Mido22/MediaRecorder-sample/blob/master/script.js If you are going to generate a recording anyway, it might be easier to record the file and then send it for processing using Amazon Transcribe rather than using Amazon Transcribe Streaming, unless you really need the real-time aspect.
