### ISSUE TITLE
Websocket connection closed with "Streaming completed successfully"

### ISSUE THREAD

**Issue by calvin-evans** [aws-samples/amazon-transcribe-websocket-static#2]
Hi, are there any resources on the websocket closure reasons? As soon as I send the first bit of data the websocket is being closed with the reason "Streaming completed successfully". 

It would make it easier to debug if I understood why that might be happening, is anyone able to share any insights?

**Comment by calvin-evans** [comment]
For anyone else with this issue - it looks like this happens if you send invalid PCM data

**Comment by dominiceden** [comment]
I too had this issue using the AWS Transcribe Medical product. The issue with this Medical product versus the regular Transcribe product is that it's very fussy about the `languageCode` (must be `en-US`) and `sampleRate` (must be `44100`) parameters. I believe this is because it's a new product and doesn't support other values yet.

I was previously using the regular Transcribe product with  `languageCode` of `en-GB` and `sampleRate` of `8000` which worked fine, but when using those values in the Transcribe Medical product I was getting the error as described in the issue almost immediately. Changing them to `en-US` and `44100` solved it.

Just putting this info out there in case it helps someone else.
